//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/Scripts/PlayerInputBindings.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputBindings: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputBindings()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputBindings"",
    ""maps"": [
        {
            ""name"": ""PlayerMouseControlls"",
            ""id"": ""6c3b2ed8-83ee-4047-b2cc-9e5612c6d01f"",
            ""actions"": [
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""fa58ada8-1061-4d00-aeca-339b0bc0f23d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""6ce95350-1001-44f9-bde4-afaabf0f100d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""98226ba7-a9dd-465c-bf36-3697db9cbeb5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""741e4535-7760-4b72-9f66-f2aec7f99e83"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMouseControlls
        m_PlayerMouseControlls = asset.FindActionMap("PlayerMouseControlls", throwIfNotFound: true);
        m_PlayerMouseControlls_MouseClick = m_PlayerMouseControlls.FindAction("MouseClick", throwIfNotFound: true);
        m_PlayerMouseControlls_MousePos = m_PlayerMouseControlls.FindAction("MousePos", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMouseControlls
    private readonly InputActionMap m_PlayerMouseControlls;
    private List<IPlayerMouseControllsActions> m_PlayerMouseControllsActionsCallbackInterfaces = new List<IPlayerMouseControllsActions>();
    private readonly InputAction m_PlayerMouseControlls_MouseClick;
    private readonly InputAction m_PlayerMouseControlls_MousePos;
    public struct PlayerMouseControllsActions
    {
        private @PlayerInputBindings m_Wrapper;
        public PlayerMouseControllsActions(@PlayerInputBindings wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseClick => m_Wrapper.m_PlayerMouseControlls_MouseClick;
        public InputAction @MousePos => m_Wrapper.m_PlayerMouseControlls_MousePos;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMouseControlls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMouseControllsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMouseControllsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMouseControllsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMouseControllsActionsCallbackInterfaces.Add(instance);
            @MouseClick.started += instance.OnMouseClick;
            @MouseClick.performed += instance.OnMouseClick;
            @MouseClick.canceled += instance.OnMouseClick;
            @MousePos.started += instance.OnMousePos;
            @MousePos.performed += instance.OnMousePos;
            @MousePos.canceled += instance.OnMousePos;
        }

        private void UnregisterCallbacks(IPlayerMouseControllsActions instance)
        {
            @MouseClick.started -= instance.OnMouseClick;
            @MouseClick.performed -= instance.OnMouseClick;
            @MouseClick.canceled -= instance.OnMouseClick;
            @MousePos.started -= instance.OnMousePos;
            @MousePos.performed -= instance.OnMousePos;
            @MousePos.canceled -= instance.OnMousePos;
        }

        public void RemoveCallbacks(IPlayerMouseControllsActions instance)
        {
            if (m_Wrapper.m_PlayerMouseControllsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMouseControllsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMouseControllsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMouseControllsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMouseControllsActions @PlayerMouseControlls => new PlayerMouseControllsActions(this);
    public interface IPlayerMouseControllsActions
    {
        void OnMouseClick(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
    }
}
